options:
  size: 2x
  max-time: 15
image: openjdk:8-jdk

pipelines:
  default:
    - parallel:
        # Unit tests
        - step:
            name: Unit Tests JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - atlas-mvn --batch-mode verify -P jacoco
            artifacts:
              - '**/target/site/jacoco/**'
        - step:
            name: Unit Tests JDK 11
            image: openjdk:11-jdk
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - atlas-mvn --batch-mode verify -P jacoco
            artifacts:
              - '**/target/site/jacoco/**'

        # Jira integration tests
        - step:
            name: IT Jira 7.13.3 JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - VERSION=7.13.3 TESTKIT_VERSION=7.12.5 bin/build/run-jira-its.sh
              - mkdir -p jira-slack-server-integration/target/failsafe-reports
              - find jira-slack-server-integration -name 'TEST*.xml' -type f -exec cp {} jira-slack-server-integration/target/failsafe-reports \;
            artifacts:
              - jira-slack-server-integration/jira-slack-server-integration-plugin/target/webdriverTests/**
        - step:
            name: IT Jira 8.3.0 JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - VERSION=8.3.0 TESTKIT_VERSION=8.1.8 bin/build/run-jira-its.sh
              - mkdir -p jira-slack-server-integration/target/failsafe-reports
              - find jira-slack-server-integration -name 'TEST*.xml' -type f -exec mv {} jira-slack-server-integration/target/failsafe-reports \;
            artifacts:
              - jira-slack-server-integration/jira-slack-server-integration-plugin/target/webdriverTests/**
        - step:
            name: IT Jira 8.3.0 JDK 11
            image: openjdk:11-jdk
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - VERSION=8.3.0 TESTKIT_VERSION=8.1.8 bin/build/run-jira-its.sh
              - mkdir -p jira-slack-server-integration/target/failsafe-reports
              - find jira-slack-server-integration -name 'TEST*.xml' -type f -exec mv {} jira-slack-server-integration/target/failsafe-reports \;
            artifacts:
              - jira-slack-server-integration/jira-slack-server-integration-plugin/target/webdriverTests/**

        # Bitbucket integration tests
        - step:
            name: IT Bb <POM version> JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - bin/build/run-bitbucket-its.sh
              - find bitbucket-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} bitbucket-slack-server-integration-plugin/target/failsafe-reports \;
            artifacts:
              - bitbucket-slack-server-integration-plugin/target/webdriverTests/**
        - step:
            name: IT Bb <POM version> JDK 11
            image: openjdk:11-jdk
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - bin/build/run-bitbucket-its.sh
              - find bitbucket-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} bitbucket-slack-server-integration-plugin/target/failsafe-reports \;
            artifacts:
              - bitbucket-slack-server-integration-plugin/target/webdriverTests/**

        # Confluence integration tests
        - step:
            name: IT Conf 6.4.3 JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - VERSION=6.4.3 bin/build/run-confluence-its.sh
              - find confluence-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} confluence-slack-server-integration-plugin/target/failsafe-reports \;
            artifacts:
              - confluence-slack-server-integration-plugin/target/webdriverTests/**
        - step:
            name: IT Conf 6.15.6 JDK 8
            caches:
              - maven
            script:
              - bin/build/install-plugin-sdk.sh
              - bin/build/install-common-modules.sh
              - bin/build/install-int-test-libs.sh
              - VERSION=6.15.6 bin/build/run-confluence-its.sh
              - find confluence-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} confluence-slack-server-integration-plugin/target/failsafe-reports \;
            artifacts:
              - confluence-slack-server-integration-plugin/target/webdriverTests/**

  # Manually started pipelines
  custom:
    Check releases:
      - step:
          script:
            - apt-get update && apt-get install -y jq
            - export JIRA_BASE_URL="https://pi-dev-sandbox.atlassian.net"
            - cd bin/release-check
            - JIRA_PROJECT="JSS" PRODUCT="jira" ./run-product-release-check.sh
            - JIRA_PROJECT="CSS" PRODUCT="confluence" ./run-product-release-check.sh
            - JIRA_PROJECT="BBSS" PRODUCT="bitbucket" ./run-product-release-check.sh
    Release Jira plugin:
      - variables:
          - name: RELEASE_VERSION
          - name: NEXT_DEVELOPMENT_VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - PLUGIN=jira-slack-server-integration/jira-slack-server-integration-plugin NAME=jira bin/build/release-single-plugin.sh
    Release Confluence plugin:
      - variables:
          - name: RELEASE_VERSION
          - name: NEXT_DEVELOPMENT_VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - PLUGIN=confluence-slack-server-integration-plugin NAME=confluence bin/build/release-single-plugin.sh
    Release Bitbucket plugin:
      - variables:
          - name: RELEASE_VERSION
          - name: NEXT_DEVELOPMENT_VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - PLUGIN=bitbucket-slack-server-integration-plugin NAME=bitbucket bin/build/release-single-plugin.sh
    # Running customized integration tests
    Jira IT JDK 8:
      - variables:
          - name: VERSION
          - name: TESTKIT_VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - bin/build/install-int-test-libs.sh
            - bin/build/run-jira-its.sh
            - mkdir -p jira-slack-server-integration/target/failsafe-reports
            - find jira-slack-server-integration -name 'TEST*.xml' -type f -exec cp {} jira-slack-server-integration/target/failsafe-reports \;
          artifacts:
            - jira-slack-server-integration/jira-slack-server-integration-plugin/target/webdriverTests/**
    Jira IT JDK 11:
      - variables:
          - name: VERSION
          - name: TESTKIT_VERSION
      - step:
          image: openjdk:11-jdk
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - bin/build/install-int-test-libs.sh
            - bin/build/run-jira-its.sh
            - mkdir -p jira-slack-server-integration/target/failsafe-reports
            - find jira-slack-server-integration -name 'TEST*.xml' -type f -exec cp {} jira-slack-server-integration/target/failsafe-reports \;
          artifacts:
            - jira-slack-server-integration/jira-slack-server-integration-plugin/target/webdriverTests/**
    Bitbucket IT JDK 8:
      - variables:
          - name: VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - bin/build/install-int-test-libs.sh
            - bin/build/run-bitbucket-its.sh
            - find bitbucket-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} bitbucket-slack-server-integration-plugin/target/failsafe-reports \;
          artifacts:
            - bitbucket-slack-server-integration-plugin/target/webdriverTests/**
    Bitbucket IT JDK 11:
      - variables:
          - name: VERSION
      - step:
          image: openjdk:11-jdk
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - bin/build/install-int-test-libs.sh
            - bin/build/run-bitbucket-its.sh
            - find bitbucket-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} bitbucket-slack-server-integration-plugin/target/failsafe-reports \;
          artifacts:
            - bitbucket-slack-server-integration-plugin/target/webdriverTests/**
    Confluence IT JDK 8:
      - variables:
          - name: VERSION
      - step:
          caches:
            - maven
          script:
            - bin/build/install-plugin-sdk.sh
            - bin/build/install-common-modules.sh
            - bin/build/install-int-test-libs.sh
            - bin/build/run-confluence-its.sh
            - find confluence-slack-server-integration-plugin -name 'TEST*.xml' -type f -exec cp {} confluence-slack-server-integration-plugin/target/failsafe-reports \;
          artifacts:
            - confluence-slack-server-integration-plugin/target/webdriverTests/**
